FROM python:3.8.0-slim

LABEL "name"="Fetch TGIK Episodes"
LABEL "maintainer"="Bryan Friedman"
LABEL "version"="0.0.1"

LABEL "com.github.actions.name"="Fetch TGIK Episodes"
LABEL "com.github.actions.description"="Fetch TGIK Episodes"
LABEL "com.github.actions.icon"="package"
LABEL "com.github.actions.color"="green"

RUN pip install
CMD [ "python", "./main.py" ]